[versions]
springBoot = "3.3.5"
springCloud = "2023.0.3"
springAi = "1.0.0-M6"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }
spring-ai-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "springAi" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
